import Head from "next/head";
import { Inter } from "@next/font/google";
import { GetStaticProps } from "next";
import axios from "axios";
import { Box, Grid } from "@chakra-ui/react";
import Card from "../components/Card";
import { AxiosResponse } from "axios";


export interface productsType {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: {
    rate: number;
    count: number;
  };
}

interface ProductsDataProps {
  products: productsType[];
}

export default function Home({ products }: ProductsDataProps) {
  return (
    <>
      <Head>
        <title>E commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box m="40px">
        <Grid templateColumns={"repeat(4, 1fr)"} gap="20px">
          {products.map((el: productsType) => (
            <Box key={el.id}>
              <Card {...el} />
            </Box>
          ))}
        </Grid>
      </Box>
    </>
  );
}

export const getStaticProps: GetStaticProps<{
  products: productsType[];
}> = async () => {
  const data: AxiosResponse<productsType[]> = await axios({
    method: "get",
    url: "http://localhost:8080/products",
  });

  return {
    props: {
      products: data?.data,
    },
  };
};
